//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z2Randomizer.WinFormUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string filePath {
            get {
                return ((string)(this["filePath"]));
            }
            set {
                this["filePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool beep {
            get {
                return ((bool)(this["beep"]));
            }
            set {
                this["beep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int tunic {
            get {
                return ((int)(this["tunic"]));
            }
            set {
                this["tunic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool spells {
            get {
                return ((bool)(this["spells"]));
            }
            set {
                this["spells"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool beam {
            get {
                return ((bool)(this["beam"]));
            }
            set {
                this["beam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool music {
            get {
                return ((bool)(this["music"]));
            }
            set {
                this["music"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int sprite {
            get {
                return ((int)(this["sprite"]));
            }
            set {
                this["sprite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int shield {
            get {
                return ((int)(this["shield"]));
            }
            set {
                this["shield"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastused {
            get {
                return ((string)(this["lastused"]));
            }
            set {
                this["lastused"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool update {
            get {
                return ((bool)(this["update"]));
            }
            set {
                this["update"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int beams {
            get {
                return ((int)(this["beams"]));
            }
            set {
                this["beams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool upac1 {
            get {
                return ((bool)(this["upac1"]));
            }
            set {
                this["upac1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lastseed {
            get {
                return ((string)(this["lastseed"]));
            }
            set {
                this["lastseed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool noflash {
            get {
                return ((bool)(this["noflash"]));
            }
            set {
                this["noflash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useCustomRooms {
            get {
                return ((bool)(this["useCustomRooms"]));
            }
            set {
                this["useCustomRooms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"Flagset\": \"RChN6EAABAViWVRLtBcbi+3mLCqCLviyAAWA\", \"Name\": \"Beginner\", \"Tooltip\"" +
            ": \"This is great for people looking for a casual experience\"}")]
        public string customizableButton1 {
            get {
                return ((string)(this["customizableButton1"]));
            }
            set {
                this["customizableButton1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"Flagset\": \"RAAN6AAFeqXtWVRstSgax+2csjw@suiyAAWA\", \"Name\": \"Standard\", \"Tooltip\"" +
            ": \"Flags for the 2023 Standard Tournament\"}")]
        public string customizableButton2 {
            get {
                return ((string)(this["customizableButton2"]));
            }
            set {
                this["customizableButton2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"Flagset\": \"hEAjMsAFerXtWVRstVdZQ+2csmv@sukyAAWA\", \"Name\": \"Max Rando\", \"Tooltip" +
            "\": \"Flags for the 2023 Max Rando Tournament\"}")]
        public string customizableButton3 {
            get {
                return ((string)(this["customizableButton3"]));
            }
            set {
                this["customizableButton3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int beepFrequency {
            get {
                return ((int)(this["beepFrequency"]));
            }
            set {
                this["beepFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int beepThreshold {
            get {
                return ((int)(this["beepThreshold"]));
            }
            set {
                this["beepThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"Flagset\": \"\", \"Name\": \"Not set\", \"Tooltip\": \"Right click to set your custom fla" +
            "gset\"}")]
        public string customizableButtonBase {
            get {
                return ((string)(this["customizableButtonBase"]));
            }
            set {
                this["customizableButtonBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useCommunityText {
            get {
                return ((bool)(this["useCommunityText"]));
            }
            set {
                this["useCommunityText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"Flagset\": \"hEAK0sAListUe5RtWbgZQ+2c4YX@4X4yAAsA\", \"Name\": \"Random%\", \"Tooltip\":" +
            " \"Is it randomized? Who knows?\"}")]
        public string customizableButton4 {
            get {
                return ((string)(this["customizableButton4"]));
            }
            set {
                this["customizableButton4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customizableButton5 {
            get {
                return ((string)(this["customizableButton5"]));
            }
            set {
                this["customizableButton5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string customizableButton6 {
            get {
                return ((string)(this["customizableButton6"]));
            }
            set {
                this["customizableButton6"] = value;
            }
        }
    }
}
